# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'h:\python\GB_homework_python\configurator_mc34063\res\dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1127, 862)
        Dialog.setStyleSheet("QDialog { background-color: #272822;}\n"
"\n"
"QTabWidget { background-color: #272822;} /* не ясно на что влияет важен порядок вложенности*/\n"
"\n"
"/******************************************************/\n"
" \n"
"/* типа глобального определения*/\n"
"QWidget {\n"
"    background-color: #333333;\n"
"    color: #fffff8;\n"
"}\n"
"/*\n"
" \n"
"QTableView::indicator:unchecked {\n"
"    background-color: #d7d6d5\n"
"}*/\n"
"\n"
"QTableView {\n"
"\n"
"/*    background-color: yellow;*/\n"
"/*    background-color: #ffaaaa;*/\n"
"/*    border-style:  2px outset red;*/\n"
"    \n"
"    background-color: #d7d6d5;\n"
"    selection-background-color: white;\n"
"}\n"
"\n"
"/* общий стиль для всех секций */\n"
"QHeaderView::section {\n"
"    min-width: 28px;\n"
"    background-color: #646464;\n"
"    padding: 4px;\n"
"    font-size: 12pt;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid #fffff8;\n"
"    border-right: 1px solid #fffff8;\n"
"    \n"
"    /*width: 180px;*/\n"
"/*    margin: 0;*/\n"
"    padding-right: 4px;\n"
"/*    white-space: nowrap;*/\n"
"}\n"
"\n"
"/*верхний ряд*/\n"
"QHeaderView::section:horizontal\n"
"{\n"
"\n"
"    height: 25px;\n"
"\n"
"/*    table-layout: auto;*/\n"
"    width: 1200px;\n"
"    border-top:1px solid #fffff8;\n"
"}\n"
"/* вертикальный  ряд*/\n"
"QHeaderView::section:vertical\n"
"{\n"
"/* работает только на 1 колонку         Width: 120px; */\n"
"\n"
"    border-left: 1px solid #fffff8;\n"
"}\n"
"/* уголок */\n"
"QTableView QTableCornerButton::section {\n"
"    background-color: #646464;\n"
"/*    background: red; */\n"
"   border: 1px solid #fffff8;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    background-color: #FFFFFF;\n"
"    color: black;\n"
"    row-width: 1200px;\n"
"};\n"
"\n"
"QTableView::item:alternate { background-color: #111111; } \n"
"\n"
"\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: rgb(242, 128, 133);\n"
"}\n"
"\n"
"/******************************************************/\n"
"\n"
"\n"
"\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 2px solid #676d73;\n"
"}\n"
" \n"
"\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 15px; /* move to the right by 5px */\n"
"}\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    color: White;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #565657, stop: 1.0 #272822);\n"
"    border: 2px solid #676d73;\n"
"    border-bottom-color: #676d73; /* same as the pane color */\n"
"    border-top-left-radius: 2px;\n"
"    border-top-right-radius: 2px;\n"
"    min-width: 25ex;\n"
"    padding:2 10px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #91969c, stop:  1.0 #676d73);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {    margin-top: 2px; /* make non-selected tabs look smaller */}\n"
"/* make use of negative margins for overlapping tabs */\n"
"QTabBar::tab:selected {     /* expand/overlap to the left and right by 4px */    \n"
"    margin-left: -4px;\n"
"    margin-right: -4px;\n"
"}\n"
"QTabBar::tab:first:selected {    margin-left: 0; /* the first selected tab has nothing to overlap with on the left */}\n"
"QTabBar::tab:last:selected {    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */}\n"
"QTabBar::tab:only-one {    margin: 0; /* if there is only one tab, we don\'t want overlapping margins */}\n"
"\n"
"/* содержимое таба */\n"
"QWidget { background-color: #272822; }\n"
"\n"
"QPushButton { color: White; background-color: Green }\n"
"\n"
"QLineEdit { background-color: #f2f2f2; }\n"
"QTextEdit { background-color: #f2f2f2; }\n"
"QLabel {  color: White; }")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(110, 360, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 121, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 30, 121, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.table_components = QtWidgets.QTableWidget(Dialog)
        self.table_components.setGeometry(QtCore.QRect(20, 80, 1071, 221))
        self.table_components.setObjectName("table_components")
        self.table_components.setColumnCount(6)
        self.table_components.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.table_components.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_components.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_components.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_components.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_components.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_components.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_components.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_components.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_components.setItem(0, 2, item)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Выбрвть файл"))
        self.pushButton_2.setText(_translate("Dialog", "Обновить"))
        item = self.table_components.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.table_components.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Назавание"))
        item = self.table_components.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Макс нарпяжение"))
        item = self.table_components.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Макс ток"))
        item = self.table_components.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Тип диода"))
        item = self.table_components.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Исполнение"))
        item = self.table_components.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Контрольные точки"))
        __sortingEnabled = self.table_components.isSortingEnabled()
        self.table_components.setSortingEnabled(False)
        self.table_components.setSortingEnabled(__sortingEnabled)
